# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Relational Data Streams in Go
description:      'Combining relational algebra with pipelines in Go.<br>C. A. R. Hoare meets E. F. Codd!'
url:              http://jonlawlor.github.io
baseurl:          '/'
paginate:         2

timezone:         America/New_York

author:
  name:           'Jonathan J Lawlor'
  url:            https://github.com/jonlawlor
  email:          jonathan.lawlor@gmail.com
